{
 "title": "Nodejs Metrics",
 "description": "Nodejs runtime metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(nodejs_active_handles, group)"
    }
   },
   {
    "name": "stack",
    "label": "Stack",
    "query": {
     "query": "label_values(nodejs_active_handles{group=\"$group\"},stack)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(nodejs_active_handles,service)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nodejs_active_handles{stack=\"$stack\",service=\"$service\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$service Nodejs Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_requests{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "nodejs_active_requests_total{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{type}}"
    },
    {
     "expr": "nodejs_active_handles_total{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} Total"
    }
   ]
  },
  {
   "title": "$service Process Heap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_heap_bytes{stack=~\"$stack\",service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service Process start time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{service=~\"$service\", stack=~\"$stack\"})*1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "$service Max file descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_max_fds{stack=~\"$stack\",service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_open_fds{stack=~\"$stack\",service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service Metrics scrape duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{stack=~\"$stack\",service=~\"$service\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "% CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{service=~\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{service=~\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} System"
    },
    {
     "expr": "rate(process_cpu_seconds_total{service=\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} Total"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} Event Loop Lag"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "External Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} External Memory"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} Total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} Used"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} Virtual"
    }
   ]
  },
  { "title": "Heap Space Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{space}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}}-{{space}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{space}}"
    }
   ]
  }
 ]
}